codecov:
  require_ci_to_pass: no
  max_report_age: off

comment: false

ignore:
  - 'tests/*.py'
  - 'update_database.py'
  - 'load-testing/*.py'
  - 'migrations/*.py'
  - 'migrations/versions/*.py'

coverage:
  precision: 2
  round: down
  status:
    project:
      default:
        target: 95
        informational: true
    patch: off
    changes: off
