name: offsets-db
channels:
  - conda-forge
  - nodefaults
dependencies:
  - aiofiles
  - alembic
  - apscheduler>=3.10.1
  - fastapi
  - fastparquet
  - fsspec
  - gunicorn
  - httpx
  - intake-parquet
  - locust==2.20
  - pandas
  - pip
  - postgresql
  - pyarrow
  - pydantic
  - pytest
  - pytest-cov
  - python=3.10
  - s3fs
  - sqlmodel
  - ujson
  - universal_pathlib
  - uvicorn
  - watchdog
  - pip:
      - .
