name: offsets-db
channels:
  - conda-forge
  - nodefaults
dependencies:
  - aiofiles
  - alembic>=1.7.5
  - apscheduler>=3.10.1
  - asyncpg>=0.27
  - fastapi>=0.94
  - fastparquet
  - gunicorn
  - httpx
  - pandas>=1.5.3
  - pandera
  - pip
  - psycopg2
  - pydantic
  - python=3.10
  - s3fs>=2023
  - sqlmodel>=0.0.11
  - ujson
  - universal_pathlib
  - uvicorn
  - pip:
      - offsets-db-data>=2023.11.10
