name: offsets-db
channels:
  - conda-forge
  - nodefaults
dependencies:
  - aiofiles
  - alembic
  - apscheduler>=3.10.1
  - fastapi
  - fastparquet
  - gunicorn
  - httpx
  - pandas
  - pandera
  - pip
  - pydantic
  - python=3.10
  - s3fs
  - sqlmodel
  - ujson
  - universal_pathlib
  - uvicorn
  - pip:
      - .
