app = "offsets-db-staging"

kill_signal = "SIGINT"
kill_timeout = 5

[build]
builder = "paketobuildpacks/builder:base"
buildpacks = ["gcr.io/paketo-buildpacks/python"]


[experimental]
allowed_public_ports = []
auto_rollback = true

[env]
OFFSETS_DB_STAGING = "true"
PORT = "8000"

[deploy]
release_command = "bash -l release.sh"


[[services]]
protocol = "tcp"
internal_port = 8000

[[services.ports]]
port = 80
handlers = ["http"]

[[services.ports]]
port = 443
handlers = ["tls", "http"]
[services.concurrency]
hard_limit = 25
soft_limit = 20

[[services.tcp_checks]]
interval = "20s"
timeout = "10s"
