app = "offsets-db-staging"

kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "dfw"

[build]
builder = "heroku/builder:24"
buildpacks = ["heroku/buildpack-python:0.17.0"]


[[vm]]
  size = "shared-cpu-2x"
  memory = "2gb"


[env]
OFFSETS_DB_STAGING = "true"
OFFSETS_DB_WEB_CONCURRENCY = "2"
OFFSETS_DB_DATABASE_POOL_SIZE = "200"
PORT = "8000"

[deploy]
release_command = "bash -l release.sh"


[processes]
  app = "gunicorn -w $OFFSETS_DB_WEB_CONCURRENCY -t 120 -k uvicorn.workers.UvicornWorker offsets_db_api.main:app --config gunicorn_config.py --access-logfile '-' --error-logfile '-'"

[[services]]
processes = ["app"]
protocol = "tcp"
internal_port = 8000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0

[[services.ports]]
port = 80
handlers = ["http"]

[[services.ports]]
port = 443
handlers = ["tls", "http"]
[services.concurrency]
type = "connections"
hard_limit = 150
soft_limit = 100

[[services.tcp_checks]]
interval = "10s"
timeout = "2s"
grace_period = "1s"
restart_limit = 0

[[services.http_checks]]
path = "/health/"
grace_period = "15s"
interval = "30s"
timeout = "10s"
