app = "offsets-db"

kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "dfw"

[build]
builder = "paketobuildpacks/builder-jammy-full:latest"
buildpacks = ["gcr.io/paketo-buildpacks/python"]


[env]
OFFSETS_DB_STAGING = "false"
PORT = "8000"

[deploy]
release_command = "bash -l release.sh"


[[services]]
protocol = "tcp"
internal_port = 8000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1

[[services.ports]]
port = 80
handlers = ["http"]

[[services.ports]]
port = 443
handlers = ["tls", "http"]
[services.concurrency]
type = "connections"
hard_limit = 2000
soft_limit = 1800

[[services.tcp_checks]]
interval = "15s"
timeout = "3s"
grace_period = "5s"
restart_limit = 0

[[services.http_checks]]
path = "/health/"
grace_period = "30s"
interval = "1m"
timeout = "15s"
