app = "offsets-db-staging"

kill_signal    = "SIGINT"
kill_timeout   = 5
primary_region = "dfw"

[[vm]]
    memory = "4gb"
    size   = "shared-cpu-2x"

[env]
    OFFSETS_DB_DATABASE_POOL_SIZE = "200"
    OFFSETS_DB_STAGING            = "true"
    OFFSETS_DB_WEB_CONCURRENCY    = "2"
    PORT                          = "8000"

[deploy]
    release_command = "bash -l release.sh"

[[services]]
    auto_start_machines  = true
    auto_stop_machines   = true
    force_https          = true
    internal_port        = 8000
    min_machines_running = 0
    processes            = ["app"]
    protocol             = "tcp"

[[services.ports]]
    handlers = ["http"]
    port     = 80

[[services.ports]]
    handlers = ["http", "tls"]
    port     = 443
[services.concurrency]
    hard_limit = 150
    soft_limit = 100
    type       = "connections"

[[services.tcp_checks]]
    grace_period  = "1s"
    interval      = "10s"
    restart_limit = 0
    timeout       = "2s"

[[services.http_checks]]
    grace_period = "15s"
    interval     = "30s"
    path         = "/health/"
    timeout      = "10s"
