app = "offsets-db"

kill_signal    = "SIGINT"
kill_timeout   = 5
primary_region = "dfw"

[[vm]]
    memory = "8gb"
    size   = "shared-cpu-4x"

[env]
    OFFSETS_DB_DATABASE_POOL_SIZE = "200"
    OFFSETS_DB_STAGING            = "false"
    OFFSETS_DB_WEB_CONCURRENCY    = "4"
    PORT                          = "8000"

[deploy]
    release_command = "bash -l release.sh"

[[services]]
    auto_start_machines  = true
    auto_stop_machines   = true
    force_https          = true
    internal_port        = 8000
    min_machines_running = 1
    processes            = ["app"]
    protocol             = "tcp"

[[services.ports]]
    handlers = ["http"]
    port     = 80

[[services.ports]]
    handlers = ["http", "tls"]
    port     = 443
[services.concurrency]
    hard_limit = 5000
    soft_limit = 4900
    type       = "connections"

[[services.tcp_checks]]
    grace_period  = "5s"
    interval      = "15s"
    restart_limit = 0
    timeout       = "3s"

[[services.http_checks]]
    grace_period = "30s"
    interval     = "1m"
    path         = "/health/"
    timeout      = "15s"
