"""add valid records url to db model

Revision ID: 00696c89404b
Revises: 89f5469d1d5b
Create Date: 2023-07-20 08:16:32.599147

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = '00696c89404b'
down_revision = '89f5469d1d5b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'file',
        sa.Column('valid_records_file_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'valid_records_file_url')
    # ### end Alembic commands ###
