"""create project_id indexes

Revision ID: 0419f13d9065
Revises: f099826eeacd
Create Date: 2023-10-31 05:01:02.647937

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0419f13d9065'
down_revision = 'f099826eeacd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clip', 'project_id', existing_type=sa.VARCHAR(), nullable=True)
    op.create_index(op.f('ix_clip_project_id'), 'clip', ['project_id'], unique=False)
    op.create_foreign_key(None, 'clip', 'project', ['project_id'], ['project_id'])
    op.alter_column('credit', 'project_id', existing_type=sa.VARCHAR(), nullable=True)
    op.create_index(op.f('ix_credit_project_id'), 'credit', ['project_id'], unique=False)
    op.create_foreign_key(None, 'credit', 'project', ['project_id'], ['project_id'])
    op.create_index(op.f('ix_project_project_id'), 'project', ['project_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_project_id'), table_name='project')
    op.drop_constraint(None, 'credit', type_='foreignkey')
    op.drop_index(op.f('ix_credit_project_id'), table_name='credit')
    op.alter_column('credit', 'project_id', existing_type=sa.VARCHAR(), nullable=False)
    op.drop_constraint(None, 'clip', type_='foreignkey')
    op.drop_index(op.f('ix_clip_project_id'), table_name='clip')
    op.alter_column('clip', 'project_id', existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
