"""use Postgres BigInt

Revision ID: 0a57cc90c01a
Revises: 6c3e6ac9445e
Create Date: 2023-06-21 14:34:02.372489

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0a57cc90c01a'
down_revision = '6c3e6ac9445e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('credit', 'quantity', existing_type=sa.INTEGER(), nullable=True)
    op.alter_column('creditstats', 'total_credits', existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('creditstats', 'total_credits', existing_type=sa.INTEGER(), nullable=False)
    op.alter_column('credit', 'quantity', existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
