"""rename registry_id to project_id

Revision ID: 1bfa52311eaf
Revises: 8e86f38862bf
Create Date: 2023-03-21 18:26:03.086797

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = '1bfa52311eaf'
down_revision = '8e86f38862bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'project', sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False)
    )
    op.drop_column('project', 'registry_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'project', sa.Column('registry_id', sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.drop_column('project', 'project_id')
    # ### end Alembic commands ###
