"""ensure project_id is unique

Revision ID: 216d52435022
Revises: f1bd9f0e086f
Create Date: 2023-05-22 17:12:48.356711

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '216d52435022'
down_revision = 'f1bd9f0e086f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'project', ['project_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project', type_='unique')
    # ### end Alembic commands ###
