"""add chunksize to file

Revision ID: 361d093e626c
Revises: 4546765e96c9
Create Date: 2023-06-14 22:10:31.223198

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '361d093e626c'
down_revision = '4546765e96c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('chunksize', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'chunksize')
    # ### end Alembic commands ###
