"""make transaction_serial_number unique

Revision ID: 3ad282e2da77
Revises: 8dafad959469
Create Date: 2023-05-25 17:13:39.456210

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '3ad282e2da77'
down_revision = '8dafad959469'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'credit', ['transaction_serial_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'credit', type_='unique')
    # ### end Alembic commands ###
