"""add retired and issued totals to the project table

Revision ID: 4546765e96c9
Revises: 3ad282e2da77
Create Date: 2023-06-06 16:22:04.708714

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4546765e96c9'
down_revision = '3ad282e2da77'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('retired', sa.Integer(), nullable=True))
    op.add_column('project', sa.Column('issued', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'issued')
    op.drop_column('project', 'retired')
    # ### end Alembic commands ###
