"""remove b-tree indexes

Revision ID: 46b4797494ca
Revises: 94e3b0854cad
Create Date: 2024-09-11 13:10:17.186167

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = '46b4797494ca'
down_revision = '94e3b0854cad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_credit_retirement_account', table_name='credit')
    op.drop_index('ix_credit_retirement_beneficiary', table_name='credit')
    op.drop_index('ix_credit_retirement_note', table_name='credit')
    op.drop_index('ix_credit_retirement_reason', table_name='credit')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_credit_retirement_reason', 'credit', ['retirement_reason'], unique=False)
    op.create_index('ix_credit_retirement_note', 'credit', ['retirement_note'], unique=False)
    op.create_index(
        'ix_credit_retirement_beneficiary', 'credit', ['retirement_beneficiary'], unique=False
    )
    op.create_index('ix_credit_retirement_account', 'credit', ['retirement_account'], unique=False)
    # ### end Alembic commands ###
