"""add_transaction_url_to_credit

Revision ID: 48c481cfb3f7
Revises: dd782201e5e5
Create Date: 2026-04-15 08:03:35.638290

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = '48c481cfb3f7'
down_revision = 'dd782201e5e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm')
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'credit', sa.Column('transaction_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credit', 'transaction_url')
    # ### end Alembic commands ###
