"""use Postgres BigInt

Revision ID: 5ca4ae602807
Revises: 0a57cc90c01a
Create Date: 2023-06-21 14:40:48.984967

"""


# revision identifiers, used by Alembic.
revision = '5ca4ae602807'
down_revision = '0a57cc90c01a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
