"""clip and project join table

Revision ID: 662a96b9d816
Revises: 0419f13d9065
Create Date: 2023-11-02 19:48:17.754290

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '662a96b9d816'
down_revision = '0419f13d9065'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'clipproject',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('clip_id', sa.Integer(), nullable=False),
        sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ['clip_id'],
            ['clip.id'],
        ),
        sa.ForeignKeyConstraint(
            ['project_id'],
            ['project.project_id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.add_column('clip', sa.Column('date', sa.DateTime(), nullable=False))
    op.add_column('clip', sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('clip', sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_index('ix_clip_project_id', table_name='clip')
    op.drop_constraint('clip_project_id_fkey', 'clip', type_='foreignkey')
    op.drop_column('clip', 'article_type')
    op.drop_column('clip', 'project_id')
    op.drop_column('clip', 'published_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'clip',
        sa.Column('published_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    )
    op.add_column('clip', sa.Column('project_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column(
        'clip', sa.Column('article_type', sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.create_foreign_key('clip_project_id_fkey', 'clip', 'project', ['project_id'], ['project_id'])
    op.create_index('ix_clip_project_id', 'clip', ['project_id'], unique=False)
    op.drop_column('clip', 'type')
    op.drop_column('clip', 'source')
    op.drop_column('clip', 'date')
    op.drop_table('clipproject')
    # ### end Alembic commands ###
