"""add project table

Revision ID: 663c273be46f
Revises:
Create Date: 2023-03-16 13:54:16.226730

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = '663c273be46f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'project',
        sa.Column('registry_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('registry', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('proponent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('protocol', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('developer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('voluntary_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('details_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('started_at', sa.Date(), nullable=True),
        sa.Column('registered_at', sa.Date(), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('recorded_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project')
    # ### end Alembic commands ###
