"""change quantity issued retired to float

Revision ID: 7880172b664a
Revises: e84bf98a5507
Create Date: 2026-03-04 17:13:52.366361

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '7880172b664a'
down_revision = 'e84bf98a5507'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm')
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'credit', 'quantity', existing_type=sa.BIGINT(), type_=sa.Double(), existing_nullable=True
    )
    op.alter_column(
        'project', 'retired', existing_type=sa.BIGINT(), type_=sa.Double(), existing_nullable=True
    )
    op.alter_column(
        'project', 'issued', existing_type=sa.BIGINT(), type_=sa.Double(), existing_nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'project', 'issued', existing_type=sa.Double(), type_=sa.BIGINT(), existing_nullable=True
    )
    op.alter_column(
        'project', 'retired', existing_type=sa.Double(), type_=sa.BIGINT(), existing_nullable=True
    )
    op.alter_column(
        'credit', 'quantity', existing_type=sa.Double(), type_=sa.BIGINT(), existing_nullable=True
    )
    # ### end Alembic commands ###
