"""allow name to be Nullable

Revision ID: 7cd293968e05
Revises: b929202eddf6
Create Date: 2023-04-21 21:52:26.494141

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '7cd293968e05'
down_revision = 'b929202eddf6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'name', existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'name', existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
