"""add total transactions

Revision ID: 89f5469d1d5b
Revises: 5ca4ae602807
Create Date: 2023-06-21 15:38:38.143262

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '89f5469d1d5b'
down_revision = '5ca4ae602807'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('creditstats', sa.Column('total_transactions', sa.Integer(), nullable=True))
    op.alter_column(
        'credit', 'quantity', existing_type=sa.INTEGER(), type_=sa.BigInteger(), nullable=True
    )
    op.alter_column(
        'creditstats',
        'total_credits',
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('creditstats', 'total_transactions')
    op.alter_column(
        'credit', 'quantity', type_=sa.INTEGER(), existing_type=sa.BigInteger(), nullable=True
    )
    op.alter_column(
        'creditstats',
        'total_credits',
        type_=sa.INTEGER(),
        existing_type=sa.BigInteger(),
        nullable=True,
    )
    # ### end Alembic commands ###
