"""Rename credit transaction fields to reflect retirement context

Revision ID: 8b97dd22cafd
Revises:
Create Date: 2024-09-05 14:30:52.228849

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8b97dd22cafd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Create pg_trgm extension
    op.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'clip',
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('is_waybacked', sa.Boolean(), nullable=True),
        sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'file',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            'status', sa.Enum('pending', 'success', 'failure', name='filestatus'), nullable=False
        ),
        sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('recorded_at', sa.DateTime(), nullable=False),
        sa.Column(
            'category',
            sa.Enum('projects', 'credits', 'clips', 'unknown', name='filecategory'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'project',
        sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('registry', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('proponent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('protocol', postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column('category', postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('listed_at', sa.Date(), nullable=True),
        sa.Column('is_compliance', sa.Boolean(), nullable=True),
        sa.Column('retired', sa.BigInteger(), nullable=True),
        sa.Column('issued', sa.BigInteger(), nullable=True),
        sa.Column('first_issuance_at', sa.Date(), nullable=True),
        sa.Column('first_retirement_at', sa.Date(), nullable=True),
        sa.Column('project_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint('project_id'),
    )
    op.create_index(op.f('ix_project_project_id'), 'project', ['project_id'], unique=True)
    op.create_table(
        'clipproject',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('clip_id', sa.Integer(), nullable=False),
        sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ['clip_id'],
            ['clip.id'],
        ),
        sa.ForeignKeyConstraint(
            ['project_id'],
            ['project.project_id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'credit',
        sa.Column('quantity', sa.BigInteger(), nullable=True),
        sa.Column('vintage', sa.Integer(), nullable=True),
        sa.Column('transaction_date', sa.Date(), nullable=True),
        sa.Column('transaction_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('retirement_account', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('retirement_beneficiary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('retirement_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('retirement_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ['project_id'],
            ['project.project_id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_credit_project_id'), 'credit', ['project_id'], unique=False)
    op.create_index(
        op.f('ix_credit_retirement_account'), 'credit', ['retirement_account'], unique=False
    )
    op.create_index(
        op.f('ix_credit_retirement_beneficiary'), 'credit', ['retirement_beneficiary'], unique=False
    )
    op.create_index(op.f('ix_credit_retirement_note'), 'credit', ['retirement_note'], unique=False)
    op.create_index(
        op.f('ix_credit_retirement_reason'), 'credit', ['retirement_reason'], unique=False
    )
    op.create_index(
        op.f('ix_credit_transaction_date'), 'credit', ['transaction_date'], unique=False
    )

    # Create GIN indexes for trigram similarity search
    op.execute(
        'CREATE INDEX idx_credit_retirement_beneficiary_trgm ON credit USING gin (retirement_beneficiary gin_trgm_ops)'
    )
    op.execute(
        'CREATE INDEX idx_credit_retirement_note_trgm ON credit USING gin (retirement_note gin_trgm_ops)'
    )
    op.execute(
        'CREATE INDEX idx_credit_retirement_account_trgm ON credit USING gin (retirement_account gin_trgm_ops)'
    )
    op.execute(
        'CREATE INDEX idx_credit_retirement_reason_trgm ON credit USING gin (retirement_reason gin_trgm_ops)'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # Remove GIN indexes
    op.execute('DROP INDEX IF EXISTS idx_credit_retirement_beneficiary_trgm')
    op.execute('DROP INDEX IF EXISTS idx_credit_retirement_note_trgm')
    op.execute('DROP INDEX IF EXISTS idx_credit_retirement_account_trgm')
    op.execute('DROP INDEX IF EXISTS idx_credit_retirement_reason_trgm')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_credit_transaction_date'), table_name='credit')
    op.drop_index(op.f('ix_credit_retirement_reason'), table_name='credit')
    op.drop_index(op.f('ix_credit_retirement_note'), table_name='credit')
    op.drop_index(op.f('ix_credit_retirement_beneficiary'), table_name='credit')
    op.drop_index(op.f('ix_credit_retirement_account'), table_name='credit')
    op.drop_index(op.f('ix_credit_project_id'), table_name='credit')
    op.drop_table('credit')
    op.drop_table('clipproject')
    op.drop_index(op.f('ix_project_project_id'), table_name='project')
    op.drop_table('project')
    op.drop_table('file')
    op.drop_table('clip')

    # Remove pg_trgm extension
    op.execute('DROP EXTENSION IF EXISTS pg_trgm')
    # ### end Alembic commands ###
