"""refactor credit and project

Revision ID: 92b239179f40
Revises: ea8221730589
Create Date: 2023-10-12 21:09:07.339316

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = '92b239179f40'
down_revision = 'ea8221730589'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('credit_transaction_serial_number_key', 'credit', type_='unique')
    op.drop_column('credit', 'details_url')
    op.drop_column('credit', 'transaction_serial_number')
    op.drop_column('file', 'chunksize')
    op.drop_column('file', 'valid_records_file_url')
    op.add_column('project', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('project', sa.Column('listed_at', sa.Date(), nullable=True))
    op.add_column('project', sa.Column('is_compliance', sa.Boolean(), nullable=True))
    op.drop_column('project', 'developer')
    op.drop_column('project', 'is_arb')
    op.drop_column('project', 'voluntary_status')
    op.drop_column('project', 'description')
    op.drop_column('project', 'id')
    op.drop_column('project', 'started_at')
    op.drop_column('project', 'registered_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'project', sa.Column('registered_at', sa.DATE(), autoincrement=False, nullable=True)
    )
    op.add_column('project', sa.Column('started_at', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('project', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column(
        'project', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        'project', sa.Column('voluntary_status', sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column('project', sa.Column('is_arb', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column(
        'project', sa.Column('developer', sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_column('project', 'is_compliance')
    op.drop_column('project', 'listed_at')
    op.drop_column('project', 'status')
    op.add_column(
        'file',
        sa.Column('valid_records_file_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column('file', sa.Column('chunksize', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column(
        'credit',
        sa.Column('transaction_serial_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        'credit', sa.Column('details_url', sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.create_unique_constraint(
        'credit_transaction_serial_number_key', 'credit', ['transaction_serial_number']
    )
    # ### end Alembic commands ###
