"""rename type to project type

Revision ID: aa61bc8eaf51
Revises: e86c17ae210b
Create Date: 2025-04-16 15:19:07.501683

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = 'aa61bc8eaf51'
down_revision = 'e86c17ae210b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm')
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'credit', 'vintage', existing_type=sa.BIGINT(), type_=sa.Integer(), existing_nullable=True
    )
    op.alter_column(
        'credit',
        'id',
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        nullable=False,
        autoincrement=True,
    )
    op.create_index(op.f('ix_credit_project_id'), 'credit', ['project_id'], unique=False)
    op.create_index(
        'ix_credit_retirement_account_gin',
        'credit',
        [sa.text('lower(retirement_account) gin_trgm_ops')],
        unique=False,
        postgresql_using='gin',
    )
    op.create_index(
        'ix_credit_retirement_beneficiary_gin',
        'credit',
        [sa.text('lower(retirement_beneficiary) gin_trgm_ops')],
        unique=False,
        postgresql_using='gin',
    )
    op.create_index(
        'ix_credit_retirement_beneficiary_harmonized_gin',
        'credit',
        [sa.text('lower(retirement_beneficiary_harmonized) gin_trgm_ops')],
        unique=False,
        postgresql_using='gin',
    )
    op.create_index(
        'ix_credit_retirement_note_gin',
        'credit',
        [sa.text('lower(retirement_note) gin_trgm_ops')],
        unique=False,
        postgresql_using='gin',
    )
    op.create_index(
        'ix_credit_retirement_reason_gin',
        'credit',
        [sa.text('lower(retirement_reason) gin_trgm_ops')],
        unique=False,
        postgresql_using='gin',
    )
    op.create_index(
        op.f('ix_credit_transaction_date'), 'credit', ['transaction_date'], unique=False
    )
    op.create_index(
        'ix_credit_transaction_type_gin',
        'credit',
        [sa.text('lower(transaction_type) gin_trgm_ops')],
        unique=False,
        postgresql_using='gin',
    )
    op.create_foreign_key(None, 'credit', 'project', ['project_id'], ['project_id'])
    op.add_column(
        'project', sa.Column('project_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    op.add_column(
        'project',
        sa.Column('project_type_source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.drop_column('project', 'type_source')
    op.drop_column('project', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column(
        'project', sa.Column('type_source', sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_column('project', 'project_type_source')
    op.drop_column('project', 'project_type')
    op.drop_constraint(None, 'credit', type_='foreignkey')
    op.drop_index('ix_credit_transaction_type_gin', table_name='credit', postgresql_using='gin')
    op.drop_index(op.f('ix_credit_transaction_date'), table_name='credit')
    op.drop_index('ix_credit_retirement_reason_gin', table_name='credit', postgresql_using='gin')
    op.drop_index('ix_credit_retirement_note_gin', table_name='credit', postgresql_using='gin')
    op.drop_index(
        'ix_credit_retirement_beneficiary_harmonized_gin',
        table_name='credit',
        postgresql_using='gin',
    )
    op.drop_index(
        'ix_credit_retirement_beneficiary_gin', table_name='credit', postgresql_using='gin'
    )
    op.drop_index('ix_credit_retirement_account_gin', table_name='credit', postgresql_using='gin')
    op.drop_index(op.f('ix_credit_project_id'), table_name='credit')
    op.alter_column(
        'credit',
        'id',
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        nullable=True,
        autoincrement=True,
    )
    op.alter_column(
        'credit', 'vintage', existing_type=sa.Integer(), type_=sa.BIGINT(), existing_nullable=True
    )
    # ### end Alembic commands ###
