"""add category to file model

Revision ID: b929202eddf6
Revises: 1bfa52311eaf
Create Date: 2023-03-22 13:31:49.964137

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b929202eddf6'
down_revision = '1bfa52311eaf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.execute("UPDATE file SET category='unknown'")
    op.alter_column('file', 'category', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'category')
    # ### end Alembic commands ###
