"""add retirement_beneficiary_harmonized

Revision ID: c05cd27127ae
Revises: 8738137f943c
Create Date: 2025-03-05 15:34:53.600631

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c05cd27127ae'
down_revision = '8738137f943c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm')
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'credit',
        sa.Column(
            'retirement_beneficiary_harmonized', sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.create_index(
        'ix_credit_retirement_beneficiary_harmonized_gin',
        'credit',
        [sa.text('lower(retirement_beneficiary_harmonized) gin_trgm_ops')],
        unique=False,
        postgresql_using='gin',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        'ix_credit_retirement_beneficiary_harmonized_gin',
        table_name='credit',
        postgresql_using='gin',
    )
    op.drop_column('credit', 'retirement_beneficiary_harmonized')
    # ### end Alembic commands ###
