"""make both category and protocol a list strings

Revision ID: d2bc99dedcf6
Revises: e0c9ea45fc91
Create Date: 2023-09-18 06:52:14.701020

"""


# revision identifiers, used by Alembic.
revision = 'd2bc99dedcf6'
down_revision = 'e0c9ea45fc91'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
