"""change_quantity_fields_to_float

Revision ID: dd782201e5e5
Revises: e7d9d6cf54c6
Create Date: 2026-04-15 07:55:28.570225

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'dd782201e5e5'
down_revision = 'e7d9d6cf54c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm')
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'credit', 'quantity', existing_type=sa.BIGINT(), type_=sa.Double(), existing_nullable=True
    )
    op.alter_column(
        'project', 'retired', existing_type=sa.BIGINT(), type_=sa.Double(), existing_nullable=True
    )
    op.alter_column(
        'project', 'issued', existing_type=sa.BIGINT(), type_=sa.Double(), existing_nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'project', 'issued', existing_type=sa.Double(), type_=sa.BIGINT(), existing_nullable=True
    )
    op.alter_column(
        'project', 'retired', existing_type=sa.Double(), type_=sa.BIGINT(), existing_nullable=True
    )
    op.alter_column(
        'credit', 'quantity', existing_type=sa.Double(), type_=sa.BIGINT(), existing_nullable=True
    )
    # ### end Alembic commands ###
