"""enable cascade on delete

Revision ID: e0c9ea45fc91
Revises: 00696c89404b
Create Date: 2023-07-20 15:33:59.813520

"""


# revision identifiers, used by Alembic.
revision = 'e0c9ea45fc91'
down_revision = '00696c89404b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
