"""initialization

Revision ID: ea8221730589
Revises: b416aeec829c
Create Date: 2023-09-18 14:51:54.127626

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ea8221730589'
down_revision = 'b416aeec829c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'credit',
        sa.Column('quantity', sa.BigInteger(), nullable=True),
        sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('vintage', sa.Integer(), nullable=True),
        sa.Column('transaction_date', sa.Date(), nullable=True),
        sa.Column('transaction_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('transaction_serial_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('details_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('recorded_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('transaction_serial_number'),
    )
    op.create_table(
        'creditstats',
        sa.Column('total_credits', sa.BigInteger(), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('registry', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('transaction_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('total_transactions', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'file',
        sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('recorded_at', sa.DateTime(), nullable=False),
        sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('chunksize', sa.Integer(), nullable=True),
        sa.Column('valid_records_file_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'project',
        sa.Column('protocol', postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column('category', postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column('retired', sa.BigInteger(), nullable=True),
        sa.Column('issued', sa.BigInteger(), nullable=True),
        sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('registry', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('proponent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('developer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('voluntary_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('started_at', sa.Date(), nullable=True),
        sa.Column('registered_at', sa.Date(), nullable=True),
        sa.Column('is_arb', sa.Boolean(), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('recorded_at', sa.DateTime(), nullable=False),
        sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('details_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('project_id'),
    )
    op.create_table(
        'projectstats',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('registry', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('total_projects', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projectstats')
    op.drop_table('project')
    op.drop_table('file')
    op.drop_table('creditstats')
    op.drop_table('credit')
    # ### end Alembic commands ###
