"""add category to project model

Revision ID: f1bd9f0e086f
Revises: 7cd293968e05
Create Date: 2023-05-17 18:19:10.830411

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f1bd9f0e086f'
down_revision = '7cd293968e05'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'project', sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'category')
    # ### end Alembic commands ###
