name: fly

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    name: deploy app
    runs-on: ubuntu-latest
    if: ${{ (contains(github.event.pull_request.labels.*.name, 'api') && github.event_name == 'pull_request') || github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref == 'refs/heads/main') }}
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Staging
        if: github.ref != 'refs/heads/main'
        run: |
          flyctl deploy --remote-only --config fly.staging.toml

      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        run: |
          flyctl deploy --remote-only --config fly.prod.toml
