name: Populate-Offsets-DB

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-west-2

jobs:
  process-archive:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3

      - name: Set up conda environment
        uses: mamba-org/provision-with-micromamba@v15
        with:
          micromamba-version: latest
          channel-priority: strict
          environment-file: envs/environment-dev.yml
          environment-name: offsets-db
          cache-env: true
          extra-specs: |
            python="3.10"

      - name: Process Projects
        run: |
          cd flows
          #  --bucket ${{ github.event.inputs.bucket }} \
          python populate_db.py \
                --pattern "s3://carbonplan-offsets-db/data/archive/????-??-??/*/projects.csv.gz" \
                --bucket "s3://carbonplan-scratch/" \
                --prefix "processed-offsets-db" \
                --api-endpoint https://offsets-db.fly.dev/projects/files
