name: Prefect

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
    branches:
      - main
  workflow_dispatch:
    inputs:
      bucket:
        description: 'S3 bucket to write to'
        required: true
        default: 's3://carbonplan-offsets-db'
  schedule:
    - cron: '0 0 * * *' # Daily “At 00:00” UTC

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-west-2
  PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
  PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}

jobs:
  flows:
    runs-on: ubuntu-latest
    if: |
      ${{ (contains(github.event.pull_request.labels.*.name, 'etl') && github.event_name == 'pull_request')
      || github.event_name == 'workflow_dispatch'
      || (github.event_name == 'push' && github.ref == 'refs/heads/main')
      || (github.event_name == 'schedule' && github.ref == 'refs/heads/main') }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3

      - name: Set up conda environment
        uses: mamba-org/provision-with-micromamba@v15
        with:
          micromamba-version: latest
          channel-priority: strict
          environment-file: envs/environment-dev.yml
          environment-name: offsets-db
          cache-env: true
          extra-specs: |
            python="3.10"

      - name: Prefect Cloud login
        run: |
          prefect config set PREFECT_API_KEY=${{ secrets.PREFECT_API_KEY }}
          prefect config set PREFECT_API_URL=${{ secrets.PREFECT_API_URL }}

      - name: Run test flows
        run: |
          cd flows
          python projects.py \
              --api-endpoint https://offsets-db-staging.fly.dev

      - name: Run flows
        if: (github.ref == 'refs/heads/main' && github.event_name == 'schedule') || github.event_name == 'workflow_dispatch'
        # env:
        #   PREFECT_TASKS_REFRESH_CACHE: true
        run: |
          cd flows
          python projects.py \
                --bucket s3://carbonplan-offsets-db \
                --all \
                --api-endpoint https://offsets-db.fly.dev
